<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.sbv.org.vn/global/remittance/securitiesposting/create/version1.0" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="sbv/global/remittance/securitiesposting/create/version1.0" xmlns:ns4="http://www.sbv.gov.vn/global/remittance/securitiesposting/version1.0" xmlns:ns3="http://www.sbv.org.vn/global/remittance/securitiesposting/version1.0" xmlns:tns="http://www.sbv.gov.vn/global/remittance/securitiesposting/version1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sbv.gov.vn/global/remittance/securitiesposting/version1.0">
    <import namespace="http://www.sbv.gov.vn/global/remittance/securitiesposting/version1.0" location="SecuritiesPosting.xsd"/>
    <message name="createPostingReq">
        <part name="Req" element="ns4:createPostingReq"/>
    </message>
    <message name="createPostingRes">
        <part name="Res" element="ns4:createPostingRes"/>
    </message>
    <portType name="PortType">
        <operation name="createPosting">
            <input message="tns:createPostingReq"/>
            <output message="tns:createPostingRes"/>
        </operation>
    </portType>
</definitions>