<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.sbv.gov.vn/global/system/ESB/T24TTBTDT/version1.0/SendToT24.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http:///www.sbv.gov.vn/global/system/ESB/T24TTBTDT/SendToT24.xsd" xmlns:ns3="http://www.sbv.gov.vn/global/system/ESB/T24TTBTDT/version1.0/BTCTPosting.xsd" xmlns:tns="http://www.sbv.gov.vn/global/system/ESB/T24TTBTDT/version1.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sbv.gov.vn/global/system/ESB/T24TTBTDT/version1.0">
    <import namespace="http://www.sbv.gov.vn/global/system/ESB/T24TTBTDT/version1.0/SendToT24.xsd" location="SendToT24.xsd"/>
    <import namespace="http://www.sbv.gov.vn/global/system/ESB/T24TTBTDT/version1.0/BTCTPosting.xsd" location="BTCTPosting.xsd"/>
    <message name="BTCTPostingRequest">
        <part name="Req" element="ns3:BTCTPostingRequest"/>
    </message>
    <message name="BTCTPostingResponse">
        <part name="Res" element="ns3:BTCTPostingResponse"/>
    </message>
    <portType name="PortType">
        <operation name="BTCTPosting">
            <input message="tns:BTCTPostingRequest"/>
            <output message="tns:BTCTPostingResponse"/>
        </operation>
    </portType>
</definitions>