<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="schema://www.sbv.gov.vn/Schema/Global/System/CSDSG4/FeeLookup.xsd" xmlns:tns="http://wsdl.www.sbv.gov.vn/schema/global/feelookup.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.www.sbv.gov.vn/schema/global/feelookup.wsdl">
    <import namespace="schema://www.sbv.gov.vn/Schema/Global/System/CSDSG4/FeeLookup.xsd" location="FeeLookup.xsd"/>
    <message name="FeeLookupRequest">
        <part name="request" element="ns:FeeLookupRequest"/>
    </message>
    <message name="FeeLookupResponse">
        <part name="response" element="ns:FeeLookupResponse"/>
    </message>
    <portType name="FeeLookup">
        <operation name="FeeLookup">
            <input message="tns:FeeLookupRequest"/>
            <output message="tns:FeeLookupResponse"/>
        </operation>
    </portType>
</definitions>