<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="http://www.sbv.gov.vn/global/CheckAccountBalance/CheckAccountBalance/version1.0" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Account/CheckAccountBalance/Schema.xsd" xmlns:tns="http://xmlns.example.com/1443594756407" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1443594756407">
    <import namespace="http://www.sbv.gov.vn/global/CheckAccountBalance/CheckAccountBalance/version1.0" location="CheckAccountBalance.xsd"/>
    <message name="CheckAccountBalanceReq">
        <part name="Req" element="ns2:getAccountBalanceTTBTReq"/>
    </message>
    <message name="CheckAccountBalanceRes">
        <part name="Res" element="ns2:getAccountBalanceTTBTRes"/>
    </message>
    <portType name="CheckAccountBalance">
        <operation name="CheckAccountBalance">
            <input message="tns:CheckAccountBalanceReq"/>
            <output message="tns:CheckAccountBalanceRes"/>
        </operation>
    </portType>
</definitions>