<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.sbv.gov.vn/global/portaldashboard/cashreserveratio/version1.0" xmlns:tns="http://xmlns.example.com/1465530979601" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1465530979601">
    <import namespace="http://www.sbv.gov.vn/global/portaldashboard/cashreserveratio/version1.0" location="CashReserveRatio.xsd"/>
    <message name="CashReserveRatioInput">
        <part name="cashReserveRatioReq" element="ns:cashReserveRatioReq"/>
    </message>
    <message name="CashReserveRatioOutput">
        <part name="cashReserveRatioRes" element="ns:cashReserveRatioRes"/>
    </message>
    <portType name="PortalDashBoard">
        <operation name="cashReserveRatio">
            <input message="tns:CashReserveRatioInput"/>
            <output message="tns:CashReserveRatioOutput"/>
        </operation>
    </portType>
</definitions>