<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.sbv.gov.vn/global/account/CSDAccountInfo/version1.0" xmlns:tns="http://xmlns.example.com/1456826082797" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1456826082797">
    <import namespace="http://www.sbv.gov.vn/global/account/CSDAccountInfo/version1.0" location="CSDAccountInfo.xsd"/>
    <message name="GetBalanceAccRequest">
        <part name="Req" element="ns:GetBalanceAccReq"/>
    </message>
    <message name="GetBalanceAccResponse">
        <part name="Res" element="ns:GetBalanceAccRes"/>
    </message>
    <portType name="PortType">
        <operation name="GetBalanceAcc">
            <input message="tns:GetBalanceAccRequest"/>
            <output message="tns:GetBalanceAccResponse"/>
        </operation>
    </portType>
</definitions>