<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="T24AccountService" targetNamespace="http://tempuri.org/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24Accounts"/>
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models"/>
            <xs:element name="InsertOrUpdateT24Account">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24Accounts" minOccurs="0" name="model" nillable="true" type="q1:T24AccountReceive"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24AccountResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" minOccurs="0" name="InsertOrUpdateT24AccountResult" nillable="true" type="q2:ResponseState"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24Accounts" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24Accounts">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels"/>
            <xs:complexType name="T24AccountReceive">
                <xs:complexContent mixed="false">
                    <xs:extension xmlns:q1="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" base="q1:BaseReceive">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="AccountName" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="AccountNo" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Account_Officer" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Account_Title_1" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Account_Title_2" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="AlternativeNo" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CategoryId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ClearedBalance" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CompanyId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Condition_Group" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Currency" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Currency_Market" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CustomerNo" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Date_Last_CR_Cust" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="InActiv_Marker" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Int_No_Booking" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Interest_Comp_Acct" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Interest_Liqu_Acct" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="LedgerBalance" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="LimitRef" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Local_Ref" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="LockedAmount" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Mnemonic" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Online_Actual_Bal" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Online_Cleared_Bal" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Open_Actual_Bal" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Open_Cleared_Bal" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Other_Officer" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Position_Type" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Posting_Restrict" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ProductId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Reconcile_Acct" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Referal_Code" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Short_Title" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Waive_Ledger_Fee" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="WorkingBalance" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Working_Balance" nillable="true" type="xs:string"/>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="T24AccountReceive" nillable="true" type="tns:T24AccountReceive"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels">
            <xs:complexType name="BaseReceive">
                <xs:sequence/>
            </xs:complexType>
            <xs:element name="BaseReceive" nillable="true" type="tns:BaseReceive"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models">
            <xs:complexType name="ResponseState">
                <xs:sequence>
                    <xs:element minOccurs="0" name="ErrorCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ErrorMessage" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PORTALID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Successful" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="T24Code" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ResponseState" nillable="true" type="tns:ResponseState"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="IT24AccountService_InsertOrUpdateT24Account_InputMessage">
        <wsdl:part element="tns:InsertOrUpdateT24Account" name="parameters"/>
    </wsdl:message>
    <wsdl:message name="IT24AccountService_InsertOrUpdateT24Account_OutputMessage">
        <wsdl:part element="tns:InsertOrUpdateT24AccountResponse" name="parameters"/>
    </wsdl:message>
    <wsdl:portType name="IT24AccountService">
        <wsdl:operation name="InsertOrUpdateT24Account">
            <wsdl:input message="tns:IT24AccountService_InsertOrUpdateT24Account_InputMessage" wsaw:Action="http://tempuri.org/IT24AccountService/InsertOrUpdateT24Account"/>
            <wsdl:output message="tns:IT24AccountService_InsertOrUpdateT24Account_OutputMessage" wsaw:Action="http://tempuri.org/IT24AccountService/InsertOrUpdateT24AccountResponse"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_IT24AccountService" type="tns:IT24AccountService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="InsertOrUpdateT24Account">
            <soap:operation soapAction="http://tempuri.org/IT24AccountService/InsertOrUpdateT24Account" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="T24AccountService">
        <wsdl:port binding="tns:BasicHttpBinding_IT24AccountService" name="BasicHttpBinding_IT24AccountService">
            <soap:address location="http://10.0.96.227:9494/T24AccountService.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>