<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.sbv.gov.vn/global/account/accountmapping/version1.0" xmlns:tns="http://xmlns.example.com/1436322400563" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1436322400563">
    <import namespace="http://www.sbv.gov.vn/global/account/accountmapping/version1.0" location="AccountMapping.xsd"/>
    <message name="GetAccountNoReq">
        <part name="AccountMappingReq" element="ns:AccountMappingReq"/>
    </message>
    <message name="GetAccountNoRes">
        <part name="AccountMappingRes" element="ns:AccountMappingRes"/>
    </message>
    <portType name="GetAccountNoPortType">
        <operation name="GetAccountNo">
            <input message="tns:GetAccountNoReq"/>
            <output message="tns:GetAccountNoRes"/>
        </operation>
    </portType>
</definitions>