<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="T24AccountInterestMonthlyService" targetNamespace="http://tempuri.org/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24AccountInterestMonthlys"/>
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models"/>
            <xs:element name="InsertOrUpdateT24AccountInterestMonthly">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24AccountInterestMonthlys" minOccurs="0" name="model" nillable="true" type="q1:T24AccountInterestMonthlyReceive"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24AccountInterestMonthlyResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" minOccurs="0" name="InsertOrUpdateT24AccountInterestMonthlyResult" nillable="true" type="q2:ResponseState"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24AccountInterestMonthlys" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24AccountInterestMonthlys">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels"/>
            <xs:complexType name="T24AccountInterestMonthlyReceive">
                <xs:complexContent mixed="false">
                    <xs:extension xmlns:q1="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" base="q1:BaseReceive">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="AccountNumber" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Interest_Amt" type="xs:long"/>
                            <xs:element minOccurs="0" name="MonthYear" nillable="true" type="xs:string"/>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="T24AccountInterestMonthlyReceive" nillable="true" type="tns:T24AccountInterestMonthlyReceive"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels">
            <xs:complexType name="BaseReceive">
                <xs:sequence/>
            </xs:complexType>
            <xs:element name="BaseReceive" nillable="true" type="tns:BaseReceive"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models">
            <xs:complexType name="ResponseState">
                <xs:sequence>
                    <xs:element minOccurs="0" name="ErrorCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ErrorMessage" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PORTALID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Successful" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="T24Code" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ResponseState" nillable="true" type="tns:ResponseState"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="IT24AccountInterestMonthlyService_InsertOrUpdateT24AccountInterestMonthly_InputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24AccountInterestMonthly"/>
    </wsdl:message>
    <wsdl:message name="IT24AccountInterestMonthlyService_InsertOrUpdateT24AccountInterestMonthly_OutputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24AccountInterestMonthlyResponse"/>
    </wsdl:message>
    <wsdl:portType name="IT24AccountInterestMonthlyService">
        <wsdl:operation name="InsertOrUpdateT24AccountInterestMonthly">
            <wsdl:input wsaw:Action="http://tempuri.org/IT24AccountInterestMonthlyService/InsertOrUpdateT24AccountInterestMonthly" message="tns:IT24AccountInterestMonthlyService_InsertOrUpdateT24AccountInterestMonthly_InputMessage"/>
            <wsdl:output wsaw:Action="http://tempuri.org/IT24AccountInterestMonthlyService/InsertOrUpdateT24AccountInterestMonthlyResponse" message="tns:IT24AccountInterestMonthlyService_InsertOrUpdateT24AccountInterestMonthly_OutputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_IT24AccountInterestMonthlyService" type="tns:IT24AccountInterestMonthlyService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="InsertOrUpdateT24AccountInterestMonthly">
            <soap:operation soapAction="http://tempuri.org/IT24AccountInterestMonthlyService/InsertOrUpdateT24AccountInterestMonthly" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="T24AccountInterestMonthlyService">
        <wsdl:port name="BasicHttpBinding_IT24AccountInterestMonthlyService" binding="tns:BasicHttpBinding_IT24AccountInterestMonthlyService">
            <soap:address location="http://localhost:11049/T24AccountInterestMonthlyService.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>