<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="sbv/global/testtemp/version1.0" xmlns:tns="http://xmlns.example.com/1430980975435" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1430980975435">
    <import namespace="sbv/global/testtemp/version1.0" location="TestTemp.xsd"/>
    <message name="MsgReq">
        <part name="Request" element="ns:TestTempReq"/>
    </message>
    <message name="MsgRes">
        <part name="Response" element="ns:TestTempRes"/>
    </message>
    <portType name="PortType">
        <operation name="Inquiry">
            <input message="tns:MsgReq"/>
            <output message="tns:MsgRes"/>
        </operation>
    </portType>
</definitions>