<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="sbv/global/remittance/fundxfer/create/version1.0" xmlns:ns4="http://www.sbv.org.vn/global/remittance/fundxfer/version1.0" xmlns:ns="sbv/global/remittance/fundxfer/version1.0" xmlns:ns3="http://www.sbv.org.vn/global/remittance/fundxfer/create/version1.0" xmlns:tns="http://xmlns.example.com/1433466938916" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.sbv.gov.vn/global/remittance/fundxfer/version1.0" targetNamespace="http://xmlns.example.com/1433466938916">
    <import namespace="http://www.sbv.gov.vn/global/remittance/fundxfer/version1.0" location="FundXfer.xsd"/>
    <message name="createFundReq">
        <part name="Req" element="ns5:createFundReq"/>
    </message>
    <message name="createFundRes">
        <part name="Res" element="ns5:createFundRes"/>
    </message>
    <portType name="PortType">
        <operation name="createFund">
            <input message="tns:createFundReq"/>
            <output message="tns:createFundRes"/>
        </operation>
    </portType>
</definitions>