<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns2="sbv/global/remittance/ftbulk/create/version1.0" xmlns:ns="sbv/global/remittance/ftbulk/version1.0" xmlns:ns4="http://www.sbv.org.vn/global/remittance/ftbulk/version1.0" xmlns:ns3="http://www.sbv.org.vn/global/remittance/ftbulk/create/version1.0" xmlns:tns="http://xmlns.example.com/1435561938245" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns5="http://www.sbv.gov.vn/global/remittance/ftbulk/version1.0" targetNamespace="http://xmlns.example.com/1435561938245">
    <import namespace="http://www.sbv.gov.vn/global/remittance/ftbulk/version1.0" location="FTBulk.xsd"/>
    <message name="createFTBulkReq">
        <part name="Req" element="ns5:createFTBulkReq"/>
    </message>
    <message name="createFTBulkRes">
        <part name="Res" element="ns5:createFTBulkRes"/>
    </message>
    <portType name="PortType">
        <operation name="createFTBulk">
            <input message="tns:createFTBulkReq"/>
            <output message="tns:createFTBulkRes"/>
        </operation>
    </portType>
</definitions>