<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.sbv.gov.vn/global/System/ESB/T24TTBTDT/CheckBalance/version1.0" xmlns:tns="http://xmlns.example.com/1443155047346" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1443155047346">
    <import namespace="http://www.sbv.gov.vn/global/System/ESB/T24TTBTDT/CheckBalance/version1.0" location="CheckBalance.xsd"/>
    <message name="CheckBalanceReq">
        <part name="Req" element="ns:CheckBalanceReq"/>
    </message>
    <message name="CheckBalanceRes">
        <part name="Res" element="ns:CheckBalanceRes"/>
    </message>
    <portType name="PortType">
        <operation name="CheckBalance">
            <input message="tns:CheckBalanceReq"/>
            <output message="tns:CheckBalanceRes"/>
        </operation>
    </portType>
</definitions>