<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="sbv/global/pingemsserver/version1.0" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1446544604197" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1446544604197">
    <import namespace="sbv/global/pingemsserver/version1.0" location="PingEMSServer.xsd"/>
    <message name="PingEMSServerReq"/>
    <message name="PingEMSServerRes">
        <part name="Res" element="ns2:Response"/>
    </message>
    <portType name="PortType">
        <operation name="PingEMSServer">
            <input message="tns:PingEMSServerReq"/>
            <output message="tns:PingEMSServerRes"/>
        </operation>
    </portType>
</definitions>