<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="schema://www.sbv.gov.vn/schema/global/account/AccountService/AccountEnq.xsd" xmlns:tns="http://wsdl.www.sbv.gov.vn/schema/global/account/AccountService/AccountService.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.www.sbv.gov.vn/schema/global/account/AccountService/AccountService.wsdl">
    <import namespace="schema://www.sbv.gov.vn/schema/global/account/AccountService/AccountEnq.xsd" location="AccountEnq.xsd"/>
    <message name="getBlockedHistoryRequest">
        <part name="request" element="ns:getBlockedHistoryRequest"/>
    </message>
    <message name="getBlockedHistoryResponse">
        <part name="response" element="ns:getBlockedHistoryResponse"/>
    </message>
    <portType name="AccountService">
        <operation name="getBlockedHistory">
            <input message="tns:getBlockedHistoryRequest"/>
            <output message="tns:getBlockedHistoryResponse"/>
        </operation>
    </portType>
</definitions>