<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Remittance/TotalInfoBidding/TotalInfoBidding.xsd" xmlns:tns="http://xmlns.example.com/1465006658302" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1465006658302">
    <import namespace="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Remittance/TotalInfoBidding/TotalInfoBidding.xsd" location="TotalInfoBidding.xsd"/>
    <message name="TotalInfoBiddingReq">
        <part name="Req" element="ns:TotalInfoBiddingReq"/>
    </message>
    <message name="TotalInfoBiddingRes">
        <part name="Res" element="ns:TotalInfoBiddingRes"/>
    </message>
    <portType name="PortType">
        <operation name="TotalInfoBidding">
            <input message="tns:TotalInfoBiddingReq"/>
            <output message="tns:TotalInfoBiddingRes"/>
        </operation>
    </portType>
</definitions>