<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns:ns2="schema://www.sbv.gov.vn/schema/global/account/AccountService/AccountActivity.xsd" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://wsdl.www.sbv.gov.vn/schema/global/account/AccountActivity/AccountActivity.wsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://wsdl.www.sbv.gov.vn/schema/global/account/AccountActivity/AccountActivity.wsdl">
    <import location="AccountEnq.xsd" namespace="schema://www.sbv.gov.vn/schema/global/account/AccountService/AccountEnq.xsd"/>
    <import location="AccountActivity.xsd" namespace="schema://www.sbv.gov.vn/schema/global/account/AccountService/AccountActivity.xsd"/>
    <message name="getAccountActivityRequest">
        <part element="ns2:getAccountActivityRequest" name="request"/>
    </message>
    <message name="getAccountActivityResponse">
        <part element="ns2:getAccountActivityResponse" name="response"/>
    </message>
    <portType name="AccountActivity">
        <operation name="getAccountActivity">
            <input message="tns:getAccountActivityRequest"/>
            <output message="tns:getAccountActivityResponse"/>
        </operation>
    </portType>
</definitions>