<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Customer/LendingCustomerInfo/Schema.xsd" xmlns:tns="http://xmlns.example.com/1458206742432" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1458206742432">
    <import namespace="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Customer/LendingCustomerInfo/Schema.xsd" location="LendingCustomerInfo.xsd"/>
    <message name="getLendingByCusCatReq">
        <part name="Req" element="ns:getLendingByCusCatReq"/>
    </message>
    <message name="getLendingByCusCatRes">
        <part name="Res" element="ns:getLendingByCusCatRes"/>
    </message>
    <portType name="PortType">
        <operation name="getLendingByCusCat">
            <input message="tns:getLendingByCusCatReq"/>
            <output message="tns:getLendingByCusCatRes"/>
        </operation>
    </portType>
</definitions>