<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Remittance/InquiryTransactionFee/InquiryTransactionFee.xsd" xmlns:tns="http://xmlns.example.com/1464591937761" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://xmlns.example.com/1464591937761">
    <import namespace="http://www.tibco.com/schemas/SG31ESBProject/SharedResource/Schema/Global/Remittance/InquiryTransactionFee/InquiryTransactionFee.xsd" location="InquiryTransactionFee.xsd"/>
    <message name="InquiryTransactionFeeReq">
        <part name="Req" element="ns:InquiryTransactionFeeReq"/>
    </message>
    <message name="InquiryTransactionFeeRes">
        <part name="Res" element="ns:InquiryTransactionFeeRes"/>
    </message>
    <portType name="PortType">
        <operation name="InquiryTransactionFee">
            <input message="tns:InquiryTransactionFeeReq"/>
            <output message="tns:InquiryTransactionFeeRes"/>
        </operation>
    </portType>
</definitions>