<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsx="http://schemas.xmlsoap.org/ws/2004/09/mex" xmlns:wsa10="http://www.w3.org/2005/08/addressing" xmlns:wsap="http://schemas.xmlsoap.org/ws/2004/08/addressing/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:tns="http://tempuri.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:msc="http://schemas.microsoft.com/ws/2005/12/wsdl/contract" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" name="T24LoanContractService" targetNamespace="http://tempuri.org/">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://tempuri.org/">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24LoanContract"/>
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models"/>
            <xs:element name="InsertOrUpdateT24LoanContractRei">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q1="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24LoanContract" minOccurs="0" name="model" nillable="true" type="q1:T24LoanContractReceive"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24LoanContractReiResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q2="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" minOccurs="0" name="InsertOrUpdateT24LoanContractReiResult" nillable="true" type="q2:ResponseState"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24LoanHolding">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q3="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24LoanContract" minOccurs="0" name="model" nillable="true" type="q3:T24LoanHoldingReceive"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24LoanHoldingResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q4="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" minOccurs="0" name="InsertOrUpdateT24LoanHoldingResult" nillable="true" type="q4:ResponseState"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24LoanForgiveless">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q5="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24LoanContract" minOccurs="0" name="model" nillable="true" type="q5:T24LoanForgivelessReceive"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="InsertOrUpdateT24LoanForgivelessResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element xmlns:q6="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" minOccurs="0" name="InsertOrUpdateT24LoanForgivelessResult" nillable="true" type="q6:ResponseState"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.microsoft.com/2003/10/Serialization/" xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="qualified" elementFormDefault="qualified" targetNamespace="http://schemas.microsoft.com/2003/10/Serialization/">
            <xs:element name="anyType" nillable="true" type="xs:anyType"/>
            <xs:element name="anyURI" nillable="true" type="xs:anyURI"/>
            <xs:element name="base64Binary" nillable="true" type="xs:base64Binary"/>
            <xs:element name="boolean" nillable="true" type="xs:boolean"/>
            <xs:element name="byte" nillable="true" type="xs:byte"/>
            <xs:element name="dateTime" nillable="true" type="xs:dateTime"/>
            <xs:element name="decimal" nillable="true" type="xs:decimal"/>
            <xs:element name="double" nillable="true" type="xs:double"/>
            <xs:element name="float" nillable="true" type="xs:float"/>
            <xs:element name="int" nillable="true" type="xs:int"/>
            <xs:element name="long" nillable="true" type="xs:long"/>
            <xs:element name="QName" nillable="true" type="xs:QName"/>
            <xs:element name="short" nillable="true" type="xs:short"/>
            <xs:element name="string" nillable="true" type="xs:string"/>
            <xs:element name="unsignedByte" nillable="true" type="xs:unsignedByte"/>
            <xs:element name="unsignedInt" nillable="true" type="xs:unsignedInt"/>
            <xs:element name="unsignedLong" nillable="true" type="xs:unsignedLong"/>
            <xs:element name="unsignedShort" nillable="true" type="xs:unsignedShort"/>
            <xs:element name="char" nillable="true" type="tns:char"/>
            <xs:simpleType name="char">
                <xs:restriction base="xs:int"/>
            </xs:simpleType>
            <xs:element name="duration" nillable="true" type="tns:duration"/>
            <xs:simpleType name="duration">
                <xs:restriction base="xs:duration">
                    <xs:pattern value="\-?P(\d*D)?(T(\d*H)?(\d*M)?(\d*(\.\d*)?S)?)?"/>
                    <xs:minInclusive value="-P10675199DT2H48M5.4775808S"/>
                    <xs:maxInclusive value="P10675199DT2H48M5.4775807S"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:element name="guid" nillable="true" type="tns:guid"/>
            <xs:simpleType name="guid">
                <xs:restriction base="xs:string">
                    <xs:pattern value="[\da-fA-F]{8}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{4}-[\da-fA-F]{12}"/>
                </xs:restriction>
            </xs:simpleType>
            <xs:attribute name="FactoryType" type="xs:QName"/>
            <xs:attribute name="Id" type="xs:ID"/>
            <xs:attribute name="Ref" type="xs:IDREF"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24LoanContract" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels.T24LoanContract">
            <xs:import namespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels"/>
            <xs:complexType name="T24LoanContractReceive">
                <xs:complexContent mixed="false">
                    <xs:extension xmlns:q1="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" base="q1:BaseReceive">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="AmountLoan" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CreatedBy" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CreatedOn" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Currency" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CustomerNo" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="DisbusementAccount" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="DisbusementType" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ExpireDate" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Id" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="InterestRate" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="IsAutoExtend" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="LoanTypeId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ModifiedBy" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ModifiedOn" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="OnMaturity" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ReasonReject" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Status" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="T24ReferenceCode" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Term" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="TermType" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Username" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ValueDate" nillable="true" type="xs:string"/>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="T24LoanContractReceive" nillable="true" type="tns:T24LoanContractReceive"/>
            <xs:complexType name="T24LoanHoldingReceive">
                <xs:complexContent mixed="false">
                    <xs:extension xmlns:q2="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" base="q2:BaseReceive">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="AmountHolding" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CreatedBy" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CreatedOn" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Currency" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="DisbusementId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="HoldingDate" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="HoldingType" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Id" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="LoanContractId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ModifiedBy" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ModifiedOn" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ReasonReject" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Status" nillable="true" type="xs:string"/>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="T24LoanHoldingReceive" nillable="true" type="tns:T24LoanHoldingReceive"/>
            <xs:complexType name="T24LoanForgivelessReceive">
                <xs:complexContent mixed="false">
                    <xs:extension xmlns:q3="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" base="q3:BaseReceive">
                        <xs:sequence>
                            <xs:element minOccurs="0" name="Amountforgiveness" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CreatedBy" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="CreatedOn" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Currency" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="DisbusementId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ForgivenessDate" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Id" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="LoanContractId" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ModifiedBy" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ModifiedOn" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="ReasonReject" nillable="true" type="xs:string"/>
                            <xs:element minOccurs="0" name="Status" nillable="true" type="xs:string"/>
                        </xs:sequence>
                    </xs:extension>
                </xs:complexContent>
            </xs:complexType>
            <xs:element name="T24LoanForgivelessReceive" nillable="true" type="tns:T24LoanForgivelessReceive"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models.EsbModels">
            <xs:complexType name="BaseReceive">
                <xs:sequence/>
            </xs:complexType>
            <xs:element name="BaseReceive" nillable="true" type="tns:BaseReceive"/>
        </xs:schema>
        <xs:schema xmlns:tns="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://schemas.datacontract.org/2004/07/SBV.Portal.Service.Models">
            <xs:complexType name="ResponseState">
                <xs:sequence>
                    <xs:element minOccurs="0" name="ErrorCode" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="ErrorMessage" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="PORTALID" nillable="true" type="xs:string"/>
                    <xs:element minOccurs="0" name="Successful" type="xs:boolean"/>
                    <xs:element minOccurs="0" name="T24Code" nillable="true" type="xs:string"/>
                </xs:sequence>
            </xs:complexType>
            <xs:element name="ResponseState" nillable="true" type="tns:ResponseState"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:message name="IT24LoanContractService_InsertOrUpdateT24LoanContractRei_InputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24LoanContractRei"/>
    </wsdl:message>
    <wsdl:message name="IT24LoanContractService_InsertOrUpdateT24LoanContractRei_OutputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24LoanContractReiResponse"/>
    </wsdl:message>
    <wsdl:message name="IT24LoanContractService_InsertOrUpdateT24LoanHolding_InputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24LoanHolding"/>
    </wsdl:message>
    <wsdl:message name="IT24LoanContractService_InsertOrUpdateT24LoanHolding_OutputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24LoanHoldingResponse"/>
    </wsdl:message>
    <wsdl:message name="IT24LoanContractService_InsertOrUpdateT24LoanForgiveless_InputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24LoanForgiveless"/>
    </wsdl:message>
    <wsdl:message name="IT24LoanContractService_InsertOrUpdateT24LoanForgiveless_OutputMessage">
        <wsdl:part name="parameters" element="tns:InsertOrUpdateT24LoanForgivelessResponse"/>
    </wsdl:message>
    <wsdl:portType name="IT24LoanContractService">
        <wsdl:operation name="InsertOrUpdateT24LoanContractRei">
            <wsdl:input wsaw:Action="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanContractRei" message="tns:IT24LoanContractService_InsertOrUpdateT24LoanContractRei_InputMessage"/>
            <wsdl:output wsaw:Action="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanContractReiResponse" message="tns:IT24LoanContractService_InsertOrUpdateT24LoanContractRei_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="InsertOrUpdateT24LoanHolding">
            <wsdl:input wsaw:Action="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanHolding" message="tns:IT24LoanContractService_InsertOrUpdateT24LoanHolding_InputMessage"/>
            <wsdl:output wsaw:Action="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanHoldingResponse" message="tns:IT24LoanContractService_InsertOrUpdateT24LoanHolding_OutputMessage"/>
        </wsdl:operation>
        <wsdl:operation name="InsertOrUpdateT24LoanForgiveless">
            <wsdl:input wsaw:Action="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanForgiveless" message="tns:IT24LoanContractService_InsertOrUpdateT24LoanForgiveless_InputMessage"/>
            <wsdl:output wsaw:Action="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanForgivelessResponse" message="tns:IT24LoanContractService_InsertOrUpdateT24LoanForgiveless_OutputMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="BasicHttpBinding_IT24LoanContractService" type="tns:IT24LoanContractService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="InsertOrUpdateT24LoanContractRei">
            <soap:operation soapAction="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanContractRei" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="InsertOrUpdateT24LoanHolding">
            <soap:operation soapAction="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanHolding" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="InsertOrUpdateT24LoanForgiveless">
            <soap:operation soapAction="http://tempuri.org/IT24LoanContractService/InsertOrUpdateT24LoanForgiveless" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="T24LoanContractService">
        <wsdl:port name="BasicHttpBinding_IT24LoanContractService" binding="tns:BasicHttpBinding_IT24LoanContractService">
            <soap:address location="http://localhost:11049/T24LoanContractService.svc"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>