<?xml version="1.0" encoding="UTF-8"?>
<!--Created by TIBCO WSDL-->
<wsdl:definitions xmlns:ns="http://www.sbv.gov.vn/global/remittance/ftbulk/version1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.sbv.org.vn/service/global/remittance/ftbulk/version1.0" xmlns:jms="http://www.tibco.com/namespaces/ws/2004/soap/binding/JMS" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:jndi="http://www.tibco.com/namespaces/ws/2004/soap/apis/jndi" name="Untitled" targetNamespace="http://www.sbv.org.vn/service/global/remittance/ftbulk/version1.0">
    <wsdl:import namespace="http://www.sbv.gov.vn/global/remittance/ftbulk/version1.0" location="../../Remittance/FTBulk/FTBulk.xsd"/>
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sbv.gov.vn/global/remittance/ftbulk/version1.0" elementFormDefault="qualified" attributeFormDefault="unqualified">
            <xs:include schemaLocation="../../../../../SharedResource/Schema/Global/Remittance/FTBulk/FTBulk.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:service name="FTBulk">
        <wsdl:port name="PortTypeEndpoint0" binding="tns:PortTypeEndpoint0Binding">
            <soap:address location=""/>
            <jms:connectionFactory>FTQueueConnectionFactory</jms:connectionFactory>
            <jms:targetAddress destination="queue">ftbulk.1.0</jms:targetAddress>
        </wsdl:port>
    </wsdl:service>
    <wsdl:portType name="PortType">
        <wsdl:operation name="createFTBulk">
            <wsdl:input message="tns:createFTBulkReq"/>
            <wsdl:output message="tns:createFTBulkRes"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="PortTypeEndpoint0Binding" type="tns:PortType">
        <soap:binding style="document" transport="http://www.tibco.com/namespaces/ws/2004/soap/binding/JMS"/>
        <jms:binding messageFormat="bytes"/>
        <wsdl:operation name="createFTBulk">
            <soap:operation style="document" soapAction="/Services/Global/Remittance/FTBulk/OperationImpl/FTBulk-service0.serviceagent/PortTypeEndpoint0/createFTBulk"/>
            <wsdl:input>
                <soap:body use="literal" parts="Req"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="Res"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:message name="createFTBulkReq">
        <wsdl:part name="Req" element="ns:createFTBulkReq"/>
    </wsdl:message>
    <wsdl:message name="createFTBulkRes">
        <wsdl:part name="Res" element="ns:createFTBulkRes"/>
    </wsdl:message>
</wsdl:definitions>